name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    repository: vindhya17/webnext
    tags: latest, ${{ github.run_number }}
     name: Publish to GitHub Packages
  uses: docker/build-push-action@v1
  with:
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
    registry: docker.pkg.github.com
    repository: ${{ github.repository }}/webnext
    tags: latest, ${{ github.run_number }}
