name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "vindhya1718" --password-stdin
        docker image build -t vindhya1718/gitaction:v1 .
        docker push vindhya1718/gitaction:v1
